spring:
  cloud:
    config:
      server:
        overrides:
          spring.datasource.url: ${DB_URL}
          spring.datasource.username: ${DB_USERNAME}
          spring.datasource.password: ${DB_PASSWORD}
          spring.rabbitmq.host: ${RABBITMQ_HOST:localhost}
          spring.rabbitmq.port: ${RABBITMQ_PORT:5672}
          spring.rabbitmq.username: ${RABBITMQ_USERNAME}
          spring.rabbitmq.password: ${RABBITMQ_PASSWORD}
          eureka.client.service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
          app.jwt.secret: ${JWT_SECRET}
          app.observability.loki-url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
