spring:
  cloud:
    config:
      server:
        overrides:
          spring.rabbitmq.host: ${RABBITMQ_HOST:rabbitmq}
          eureka.client.service-url.defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
          app.observability.loki-url: ${LOKI_URL:http://loki:3100/loki/api/v1/push}
