spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
    compatibility-verifier:
      enabled: false

server:
  port: ${CONFIG_SERVER_PORT:8762}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    probes:
      enabled: true
