server:
  port: ${ORDER_SERVICE_PORT:8084}

app:
  cart-service:
    base-url: ${CART_SERVICE_BASE_URL:http://localhost:8083}
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}
  rabbitmq:
    order-exchange: order.exchange
    stock-exchange: stock.exchange
    payment-exchange: payment.exchange
    order-created-queue: order.created.queue
    order-created-routing-key: order.created
    order-cancelled-queue: order.cancelled.queue
    order-cancelled-routing-key: order.cancelled
    stock-failed-queue: stock.failed.queue
    stock-failed-routing-key: stock.failed
    stock-released-queue: stock.released.queue
    stock-released-routing-key: stock.released
    payment-success-queue: payment.success.queue
    payment-success-routing-key: payment.success
