server:
  port: 8086

spring:
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/n11bc}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: ${ORDER_JPA_DDL_AUTO:update}
    show-sql: ${ORDER_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/microservice-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/microservice-realm/protocol/openid-connect/certs}
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    probes:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

app:
  cart-service:
    base-url: ${CART_SERVICE_BASE_URL:http://localhost:8085}
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8083}
  rabbitmq:
    order-exchange: order.exchange
    stock-exchange: stock.exchange
    order-created-queue: order.created.queue
    order-created-routing-key: order.created
    order-cancelled-queue: order.cancelled.queue
    order-cancelled-routing-key: order.cancelled
    stock-failed-queue: stock.failed.queue
    stock-failed-routing-key: stock.failed
    stock-released-queue: stock.released.queue
    stock-released-routing-key: stock.released
