# user-service.yml (config server'da)

server:
  port: 8083

spring:
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://localhost:5432/n11bc}
    username: ${SUPABASE_USER:postgres}
    password: ${SUPABASE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

app:
  jwt:
    secret: fGoO74w9ffVJDITF2xDhRRPshvSqjKvpCoAvQqsCHkI=
    expiration-ms: 86400000
  refresh-token:
    expiration-ms: 604800000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
