server:
  port: ${USER_SERVICE_PORT:8081}

app:
  jwt:
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  refresh-token:
    expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS:604800000}

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: basic
